### PR TITLE
chore: recruitment landing page added

### PR DESCRIPTION
**Pull request by Rakib0101**

### CODE REVIEW

**Comment by Rakib0101** [comment]
@devzakir vai, I updated design after getting feedback from zafor vai, you can review now

**Comment by devzakir** [comment]
please rename the page name to "recruitment software for small business owner" and link under use cases

**Review by devzakir — CHANGES_REQUESTED** [review]
Please add the necessary changes that were discussed during the last meeting.

**Comment by devzakir** [comment]
@Rakib0101 bhai, conflict ache.

**Comment by Rakib0101** [comment]
@devzakir conflicts fix kore dichi vai, akhon merge korte paren, just space related conflict chilo

**Pull request merged**
